# Generated by Django 6.0.6 on 2026-06-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('solid_wood', 'Solid Wood'), ('plywood', 'Plywood / Sheet'), ('hardware', 'Hardware'), ('consumable', 'Consumable'), ('steel', 'Steel'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('wood_type', models.CharField(blank=True, help_text='e.g. Pinewood, Rubber Wood, Sal, Teak, Eucalyptus', max_length=100)),
                ('wood_grade', models.CharField(choices=[('AD', 'AD - Air Dried'), ('KD', 'KD - Kiln Dried'), ('BWR', 'BWR - Boiling Water Resistant'), ('BWP', 'BWP - Marine Grade'), ('COM', 'Commercial Grade'), ('NA', 'Not Applicable')], default='NA', max_length=10)),
                ('width_mm', models.FloatField(default=0, help_text='Width in mm (for solid wood: actual width)')),
                ('height_mm', models.FloatField(default=0, help_text='Height in mm (for solid wood: actual height)')),
                ('thickness_mm', models.FloatField(default=0, help_text='Thickness in mm (for plywood/sheet only)')),
                ('uom', models.CharField(choices=[('CFT', 'CFT - Cubic Feet'), ('SQM', 'SQM - Square Meter'), ('KG', 'KG - Kilogram'), ('NOS', 'NOS - Numbers'), ('MTR', 'MTR - Meter'), ('SQF', 'SQF - Square Feet')], default='CFT', max_length=10)),
                ('rate', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_method', models.CharField(choices=[('per_sqm_base', 'Per SQM Base Area'), ('per_sqm_total', 'Per SQM Total Area'), ('per_cbm', 'Per CBM × factor'), ('per_ton', 'Per Ton weight'), ('per_runner_qty', 'Runner qty × W_runner qty'), ('per_od_l', 'ROUNDUP(OD_L / pitch)'), ('manual', 'Manual entry only')], default='manual', max_length=30)),
                ('calc_factor', models.FloatField(default=1.0, help_text='Multiplier for calculation')),
                ('calc_pitch', models.FloatField(default=0, help_text='Pitch for OD_L based calc')),
                ('include_by_default', models.BooleanField(default=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_config', to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight_from', models.FloatField()),
                ('weight_to', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('deck_w', models.FloatField(default=150)),
                ('deck_h', models.FloatField(default=50)),
                ('runner_w', models.FloatField(default=75)),
                ('runner_h', models.FloatField(default=100)),
                ('l_runner_w', models.FloatField(default=100)),
                ('l_runner_h', models.FloatField(default=100)),
                ('beading_w', models.FloatField(default=75)),
                ('beading_h', models.FloatField(default=50)),
                ('wall_t', models.FloatField(default=8)),
                ('use_l_runner', models.BooleanField(default=False)),
                ('deck_pitch', models.FloatField(default=140)),
                ('l_runner_pitch', models.FloatField(default=500)),
                ('w_runner_pitch', models.FloatField(default=600)),
                ('lb_l_pitch', models.FloatField(default=700)),
                ('lb_h_pitch', models.FloatField(default=900)),
                ('wb_w_pitch', models.FloatField(default=700)),
                ('wb_h_pitch', models.FloatField(default=500)),
                ('top_bl_pitch', models.FloatField(default=600)),
                ('top_bw_pitch', models.FloatField(default=700)),
                ('top_chock_pitch', models.FloatField(default=500)),
                ('bot_chock_pitch', models.FloatField(default=500)),
                ('lashing_pitch', models.FloatField(default=600)),
                ('overhead_pct', models.FloatField(default=7.0)),
                ('margin_pct', models.FloatField(default=25.0)),
                ('gst_pct', models.FloatField(default=12.0)),
                ('wastage_pct', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beading_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beading_rules', to='materials.material')),
                ('chock_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chock_rules', to='materials.material')),
                ('deck_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck_rules', to='materials.material')),
                ('l_runner_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_runner_rules', to='materials.material')),
                ('runner_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_rules', to='materials.material')),
                ('top_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_rules', to='materials.material')),
                ('wall_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_rules', to='materials.material')),
            ],
            options={
                'ordering': ['weight_from'],
            },
        ),
    ]
