# Generated by Django 6.0.6 on 2026-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Config', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cft_wastage_pct', models.FloatField(default=5.0, help_text='Wastage % added to CFT calculation (5 = 5%)')),
                ('cft_conversion', models.FloatField(default=35.315, help_text='Cubic meter to CFT conversion (35.315 standard)')),
                ('sqm_wastage_pct', models.FloatField(default=5.0, help_text='Wastage % added to SQM calculation')),
                ('steel_wastage_pct', models.FloatField(default=2.0, help_text='Wastage % for steel calculations')),
                ('input_unit', models.CharField(choices=[('mm', 'Millimeter (mm)'), ('ft', 'Feet (ft)'), ('inch', 'Inches (inch)')], default='mm', help_text='Unit of dimensions customer provides', max_length=10)),
                ('overhead_pct', models.FloatField(default=7.0)),
                ('margin_pct', models.FloatField(default=25.0)),
                ('gst_pct', models.FloatField(default=12.0)),
                ('labour_rate_per_hour', models.FloatField(default=100.0)),
                ('labour_hours_default', models.FloatField(default=8.0)),
                ('lashing_belts_per_ton', models.FloatField(default=2.0, help_text='Minimum lashing belts per ton of weight')),
                ('silica_gel_grams_per_cbm', models.FloatField(default=500.0, help_text='Silica gel grams per CBM (500g standard)')),
                ('silica_gel_packet_grams', models.FloatField(default=50.0, help_text='Weight per packet in grams (50g standard)')),
                ('nail_qty_per_sqm', models.FloatField(default=1.0, help_text='Nails quantity per SQM base area')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formula Configuration',
            },
        ),
    ]
