# Generated by Django 6.0.6 on 2026-06-17 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('design_review', 'Design Review'), ('sent', 'Sent to Customer'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=20)),
                ('engineer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='clients.client')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.FloatField(default=0)),
                ('overhead_pct', models.FloatField(default=7)),
                ('overhead_amount', models.FloatField(default=0)),
                ('margin_pct', models.FloatField(default=25)),
                ('margin_amount', models.FloatField(default=0)),
                ('before_gst', models.FloatField(default=0)),
                ('gst_pct', models.FloatField(default=12)),
                ('gst_amount', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='rfq.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='BoxDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('box_id_length', models.FloatField()),
                ('box_id_width', models.FloatField()),
                ('box_id_height', models.FloatField()),
                ('box_od_length', models.FloatField(default=0)),
                ('box_od_width', models.FloatField(default=0)),
                ('box_od_height', models.FloatField(default=0)),
                ('weight_kg', models.FloatField()),
                ('access_type', models.CharField(choices=[('2_access', '2 Access (Runners)'), ('4_access', '4 Access (Blocks)')], default='2_access', max_length=20)),
                ('shipment_type', models.CharField(choices=[('domestic', 'Domestic'), ('export', 'Export / International')], default='export', max_length=20)),
                ('volume_cbm', models.FloatField(default=0)),
                ('total_area_sqm', models.FloatField(default=0)),
                ('base_area_sqm', models.FloatField(default=0)),
                ('override_deck_w', models.FloatField(blank=True, null=True)),
                ('override_deck_h', models.FloatField(blank=True, null=True)),
                ('override_runner_w', models.FloatField(blank=True, null=True)),
                ('override_runner_h', models.FloatField(blank=True, null=True)),
                ('override_l_runner_w', models.FloatField(blank=True, null=True)),
                ('override_l_runner_h', models.FloatField(blank=True, null=True)),
                ('override_beading_w', models.FloatField(blank=True, null=True)),
                ('override_beading_h', models.FloatField(blank=True, null=True)),
                ('override_wall_t', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(default=0)),
                ('edited_bom', models.TextField(blank=True, null=True)),
                ('edited_totals', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='rfq.rfq')),
            ],
        ),
    ]
