# Generated by Django 6.0.6 on 2026-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdesign',
            name='packing_type',
            field=models.CharField(choices=[('box', 'Wooden Box'), ('pallet', 'Pallet Only'), ('box_pallet', 'Box + Pallet')], default='box', max_length=20),
        ),
        migrations.AddField(
            model_name='boxdesign',
            name='pallet_deck_type',
            field=models.CharField(default='auto', max_length=20),
        ),
    ]
